package com.lifengdi.blog.bean;

import java.util.Date;

public class User extends UserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.nickName
	 * @mbg.generated
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.headerImg
	 * @mbg.generated
	 */
	private String headerimg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.sex
	 * @mbg.generated
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.sign
	 * @mbg.generated
	 */
	private String sign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.random
	 * @mbg.generated
	 */
	private String random;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.isAdmin
	 * @mbg.generated
	 */
	private Integer isadmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.roleId
	 * @mbg.generated
	 */
	private Integer roleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.aboutId
	 * @mbg.generated
	 */
	private Integer aboutid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.createTime
	 * @mbg.generated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.modifyTime
	 * @mbg.generated
	 */
	private Date modifytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.lastLoginTime
	 * @mbg.generated
	 */
	private Date lastlogintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.intro
	 * @mbg.generated
	 */
	private String intro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
	 * @return  the value of t_user.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
	 * @param name  the value for t_user.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.nickName
	 * @return  the value of t_user.nickName
	 * @mbg.generated
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.nickName
	 * @param nickname  the value for t_user.nickName
	 * @mbg.generated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.headerImg
	 * @return  the value of t_user.headerImg
	 * @mbg.generated
	 */
	public String getHeaderimg() {
		return headerimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.headerImg
	 * @param headerimg  the value for t_user.headerImg
	 * @mbg.generated
	 */
	public void setHeaderimg(String headerimg) {
		this.headerimg = headerimg == null ? null : headerimg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.sex
	 * @return  the value of t_user.sex
	 * @mbg.generated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.sex
	 * @param sex  the value for t_user.sex
	 * @mbg.generated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.sign
	 * @return  the value of t_user.sign
	 * @mbg.generated
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.sign
	 * @param sign  the value for t_user.sign
	 * @mbg.generated
	 */
	public void setSign(String sign) {
		this.sign = sign == null ? null : sign.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.random
	 * @return  the value of t_user.random
	 * @mbg.generated
	 */
	public String getRandom() {
		return random;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.random
	 * @param random  the value for t_user.random
	 * @mbg.generated
	 */
	public void setRandom(String random) {
		this.random = random == null ? null : random.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.isAdmin
	 * @return  the value of t_user.isAdmin
	 * @mbg.generated
	 */
	public Integer getIsadmin() {
		return isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.isAdmin
	 * @param isadmin  the value for t_user.isAdmin
	 * @mbg.generated
	 */
	public void setIsadmin(Integer isadmin) {
		this.isadmin = isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.roleId
	 * @return  the value of t_user.roleId
	 * @mbg.generated
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.roleId
	 * @param roleid  the value for t_user.roleId
	 * @mbg.generated
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.aboutId
	 * @return  the value of t_user.aboutId
	 * @mbg.generated
	 */
	public Integer getAboutid() {
		return aboutid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.aboutId
	 * @param aboutid  the value for t_user.aboutId
	 * @mbg.generated
	 */
	public void setAboutid(Integer aboutid) {
		this.aboutid = aboutid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.status
	 * @return  the value of t_user.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.status
	 * @param status  the value for t_user.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.createTime
	 * @return  the value of t_user.createTime
	 * @mbg.generated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.createTime
	 * @param createtime  the value for t_user.createTime
	 * @mbg.generated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.modifyTime
	 * @return  the value of t_user.modifyTime
	 * @mbg.generated
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.modifyTime
	 * @param modifytime  the value for t_user.modifyTime
	 * @mbg.generated
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.lastLoginTime
	 * @return  the value of t_user.lastLoginTime
	 * @mbg.generated
	 */
	public Date getLastlogintime() {
		return lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.lastLoginTime
	 * @param lastlogintime  the value for t_user.lastLoginTime
	 * @mbg.generated
	 */
	public void setLastlogintime(Date lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.intro
	 * @return  the value of t_user.intro
	 * @mbg.generated
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.intro
	 * @param intro  the value for t_user.intro
	 * @mbg.generated
	 */
	public void setIntro(String intro) {
		this.intro = intro == null ? null : intro.trim();
	}
}