package com.lifengdi.blog.bean;

public class UserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.loginId
	 * @mbg.generated
	 */
	private String loginid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.loginId
	 * @return  the value of t_user.loginId
	 * @mbg.generated
	 */
	public String getLoginid() {
		return loginid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.loginId
	 * @param loginid  the value for t_user.loginId
	 * @mbg.generated
	 */
	public void setLoginid(String loginid) {
		this.loginid = loginid == null ? null : loginid.trim();
	}
}